version: '3.7'

services:
  app:
    build: . 
    ports:
      - 8080:8080
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: secret
       MYSQL_DB: movies 

  mysql:
    image: mysql:5.7
    volumes:
      - film-db-mysql-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: movies 

volumes:
  film-db-mysql-data: